import type { Model } from "../../types/index";
import carImage from "../../assets/Images/car1.png";

const ModelData: Model[] = [
  {
    id: 1,
    name: "ELANTRA",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 2,
    name: "ELANTRA",
    class: "Премиум",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 3,
    name: "ELANTRA",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 4,
    name: "i30 N",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 5,
    name: "ELANTRA",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 6,
    name: "ELANTRA",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 7,
    name: "ELANTRA",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 8,
    name: "i30 N",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 9,
    name: "ELANTRA",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 10,
    name: "ELANTRA",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 5,
    name: "ELANTRA",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 6,
    name: "ELANTRA",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 7,
    name: "ELANTRA",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 8,
    name: "i30 N",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 9,
    name: "ELANTRA",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
  {
    id: 10,
    name: "ELANTRA",
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
  },
];

export default ModelData;
