import type { Model } from "../../types/index";
import carImage from "../../assets/Images/car1.png";

const ModelData: Model[] = [
  {
    id: 1,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 2,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Премиум",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 3,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 4,
    name: "i30 N",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 5,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 6,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 7,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 8,
    name: "i30 N",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 9,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 10,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 11,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 12,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 13,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 14,
    name: "i30 N",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 15,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
  {
    id: 16,
    name: "ELANTRA",
    carNumber: "K 761 HA 73",
    fuel: 100,
    class: "Эконом",
    minPrice: "10 000",
    maxPrice: "25 000",
    image: carImage,
    color: ["Голубой", "Красный"],
  },
];

export default ModelData;
